name: Deduplicate Log

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main  # 确保使用正确的分支名称

    - name: Deduplicate Log.list
      run: |
        sort -u -o Rule/Log.list Rule/Log.list

    - name: Remove Empty Lines
      run: |
        sed -i '/^[[:space:]]*$/d' Rule/Log.list

    - name: Add DOMAIN-SUFFIX if missing
      run: |
        awk '!/^DOMAIN-SUFFIX,/{print "DOMAIN-SUFFIX," $0; next}1' Rule/Log.list > temp.list && mv temp.list Rule/Log.list

    - name: Commit and push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 自动生成的 GITHUB_TOKEN
      - name: Set Git configuration
        run: |
          git config --global user.email "msosjaahwwj@gmail.com"
          git config --global user.name "Github Action"

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git add Rule/Proxy.list
            git commit -m "自动处理 Log.list"
            git push origin main
          else
            echo "No changes to commit"
          fi