name: Deduplicate Log

on: 
  push:
    branches:
      - main  # 将 'main' 改为你想要监控的分支

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: sed -i '/^[[:space:]]*$/d' Rule/Log.list
        continue-on-error: true

      - run: awk '!/^DOMAIN-SUFFIX,/{print "DOMAIN-SUFFIX," $0; next}1' Rule/Log.list > temp.list && mv temp.list Rule/Log.list

      - run: sed -E -i '' 's/^([a-z0-9-]+\.)?([a-z0-9-]+\.[a-z]+(\.[a-z]+)?),*$/\2/' Rule/Log.list

      - run: sort -u -o Rule/Log.list Rule/Log.list

      - run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add Rule/Log.list
          git commit -m "Automatically process Log"
          git push origin HEAD:main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}