name: Deduplicate Log

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}  # 使用当前分支名称
    - name: 删除空行
      run: |
        sed -i '/^[[:space:]]*$/d' Rule/Log.list
    - name: 添加前缀
      run: |
        awk '!/^DOMAIN-SUFFIX,/{print "DOMAIN-SUFFIX," $0; next}1' Rule/Log.list > temp.list && mv temp.list Rule/Log.list
    - name: 去重
      run: |
        sort -u -o Rule/Log.list Rule/Log.list
    - name: Commit and push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "msosjaahwwj@gmail.com"
        git config --global user.name "Github Action"
        git add Rule/Log.list
        git commit -m "自动处理 Log"
        git pull origin ${{ github.ref }}
        git push origin ${{ github.ref }} --force