name: Deduplicate Log

on: [push]

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deduplicate Log.list
      run: |
        sort -u Rule/Log.list -o Rule/Log.list

    - name: Remove Empty Lines
      run: |
        sed -i '/^[[:space:]]*$/d' Rule/Log.list

    - name: Commit and push if changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git commit -m "Deduplicate and remove empty lines from Log.list" || exit 0   # 如果没有变化则退出
        git push