name: Deduplicate Log

on: [push]

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main  # 确保使用正确的分支名称

    - name: Deduplicate Log.list
      run: |
        sort -u Rule/Log.list -o Rule/Log.list

    - name: Remove Empty Lines
      run: |
        sed -i '/^[[:space:]]*$/d' Rule/Log.list

    - name: Add DOMAIN-SUFFIX if missing
      run: |
        awk '!/^DOMAIN-SUFFIX,/{print "DOMAIN-SUFFIX," $0; next}1' Rule/Log.list > temp.list && mv temp.list Rule/Log.list

    - name: Commit and push if changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 自动生成的 GITHUB_TOKEN
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git checkout main  # 确保在 main 分支上
        git add -A
        git commit -m "Deduplicate and remove empty lines from Log.list, add DOMAIN-SUFFIX if missing" || exit 0   # 如果没有变化则退出
        git push origin main  # 确保推送到正确的分支