name: Update Log

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update_log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delay for 10 seconds
        run: sleep 10

      - name: Process Log.list
        run: |
          # 删除空行和空格，提取所有二级域名
          sed '/^[[:space:]]*$/d' Rule/Log.list | \
          awk -F, '{split($NF, parts, "."); if (length(parts) > 2) {print parts[length(parts)-1] "." parts[length(parts)];} else {print $NF;}}' | \
          grep -v 'xn--' > Rule/Log.temp.list

          # 每行开头添加规则类型
          sed -i 's/^/DOMAIN-SUFFIX,/' Rule/Log.temp.list

          # 排序并去重
          sort Rule/Log.temp.list | uniq > Rule/Log.list

          # 删除临时文件
          rm Rule/Log.temp.list

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      - name: Check for changes and commit if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Rule/Log.list
          if ! git diff --cached --quiet; then
            git commit -m "Auto Update Log.list"
            git push origin HEAD:main --force
          else
            echo "No changes to commit"
          fi
