name: Deduplicate Log

on:
  push:
    branches:
      - main

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delay for 10 seconds
        run: sleep 10

      - name: Remove Empty Lines
        run: sed -i '/^[[:space:]]*$/d' Rule/Log.list

      - name: Display file content after removing empty lines
        run: cat Rule/Log.list

      - name: Add DOMAIN-SUFFIX if missing
        run: awk '!/^DOMAIN-SUFFIX,/{print "DOMAIN-SUFFIX," $0; next}1' Rule/Log.list > temp.list && mv temp.list Rule/Log.list

      - name: Display file content after adding DOMAIN-SUFFIX
        run: cat Rule/Log.list

      - name: Convert third-level domains to second-level domains
        run: sed -E 's/^([a-z0-9-]+\.)?([a-z0-9-]+\.[a-z]+(\.[a-z]+)?),*$/\2/' Rule/Log.list > temp.list && mv temp.list Rule/Log.list

      - name: Display file content after converting third-level domains to second-level domains
        run: cat Rule/Log.list

      - name: Deduplicate Log.list
        run: sort -u -o Rule/Log.list Rule/Log.list

      - name: Display file content after deduplication
        run: cat Rule/Log.list

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git branch -a
          git status

      - name: Commit and force push to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Rule/Log.list
          git commit -m "Automatically process Log"
          git push origin HEAD:main --force