name: Deduplicate Rule Files

on:
  workflow_dispatch: # 仅在手动触发时执行

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main  # Ensure to use the correct branch name

    - name: Deduplicate Rule Files
      run: |
        for file in Rule/*.list; do
          sort -u -o "$file" "$file"
          sed -i '/^[[:space:]]*$/d' "$file"
        done

    - name: Commit and push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "msosjaahwwj@gmail.com"
        git config --global user.name "Github Action"
        git fetch origin main
        git checkout main
        
        # Add changes and check if there are any changes to commit
        git add Rule/*.list
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m "Deduplicate Rule Files"
          git pull origin main --rebase
          git push origin main
        fi
