name: Deduplicate Log

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deduplicate_and_filter_domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delay for 10 seconds
        run: sleep 10

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install requests

      - name: Process Log.list
        run: |
          # 删除空行和空格，提取所有二级域名
          sed '/^[[:space:]]*$/d' Rule/Log.list | \
          awk -F, '{split($NF, parts, "."); if (length(parts) > 2) {print parts[length(parts)-1] "." parts[length(parts)];} else {print $NF;}}' | \
          grep -v 'xn--' > Rule/Log.temp.list

          # 每行开头添加规则类型
          sed -i 's/^/DOMAIN-SUFFIX,/' Rule/Log.temp.list

      - name: Create filter script
        run: |
          echo "import requests

def get_domain_location(domain):
    response = requests.get(f'https://ipwhois.app/json/{domain}')
    data = response.json()
    country = data.get('country_code', 'Unknown')
    return country

with open('Rule/Log.temp.list', 'r') as file:
    domains = [line.strip().split(',')[1] for line in file]

filtered_domains = []

for domain in domains:
    country = get_domain_location(domain)
    if country not in ['CN']:
        filtered_domains.append(domain)

with open('Rule/Log.list', 'w') as file:
    for domain in filtered_domains:
        file.write(f'DOMAIN-SUFFIX,{domain}\\n')" > filter_domains.py

      - name: Run filter script
        run: python filter_domains.py

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      - name: Commit and force push to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Rule/Log.list
          git commit -m "Auto Update Log.list"
          git push origin HEAD:main --force