name: Process DIRECT.list

on:
  schedule:
    - cron: '0 13 * * *'  # 每天下午1点执行

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Process file
        run: |
          sed -i 's/, /,/g' Rule/DIRECT.list  # 去除逗号后的空格
          sort -u -o Rule/DIRECT.list Rule/DIRECT.list  # 去重
          
      - name: Commit changes
        run: |
          git config --global user.email "msosjaahwwj@gmail.com"
          git config --global user.name "EAlyce"
          git add Rule/DIRECT.list
          git commit -m "Remove comma spaces and deduplicate in DIRECT.list"
          git push
