name: Merge Crypto

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delay for 10 seconds
        run: sleep 10

      - name: Download and combine lists from multiple sources
        run: |
          # Download and combine lists from multiple sources
          curl -sSfL https://raw.githubusercontent.com/yuumimi/rules/release/loon/category-cryptocurrency.txt \
          https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Crypto.list \
          https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Crypto/Crypto.list \
          https://raw.githubusercontent.com/EAlyce/conf/main/Rule/RedotPay.list \
          https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Cryptocurrency/Cryptocurrency.list \
          | grep -v '^#' | grep -v '^$' | \
          # Remove non-printing characters and extra spaces
          tr -d '\r' | tr -d '\t' | tr -s ' ' > Rule/Crypto.list

      - name: Download and integrate lists from LeiyuG/Surge repository
        run: |
          # Fetch all list files from LeiyuG/Surge repository's rules directory
          curl -s https://api.github.com/repos/LeiyuG/Surge/contents/rules | \
          grep '"download_url"' | \
          cut -d '"' -f 4 | \
          grep '\.list$' | \
          while read -r file; do
            curl -sSfL "$file" | grep -v '^#' | grep -v '^$' | tr -d '\r' | tr -d '\t' | tr -s ' ' >> Rule/Crypto.list
          done

      - name: Clean and preprocess the list
        run: |
          # Remove lines containing '/' or '*', replace ',.' with ',', and deduplicate
          sed '/[\/\*]/d' Rule/Crypto.list | sed 's/,\.//g' | sort | uniq > Rule/Crypto_cleaned.list
          
          # Replace the cleaned list with the final result
          mv Rule/Crypto_cleaned.list Rule/Crypto.list

      - name: Check if there are changes
        run: |
          git status
          git diff

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          
      - name: Commit and push changes if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Rule/Crypto.list
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update Crypto.list"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
