name: Merge_AI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get and merge domains from source files
        run: |
          {
           curl -sSfL "https://ruleset.skk.moe/List/non_ip/ai.conf" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Loon/Rule/AI.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Copilot/Copilot.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/Repcz/Tool/974e9a365c00bb30b00ee8054968047ea6072caa/Surge/Rules/AI.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/EAlyce/conf/main/Rule/ai.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/xOS/Config/5d35f08d4d1c455a1774b9bfcf0fed898f583a93/RuleSet/CloudFlare.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/Repcz/Tool/6409f27cb9d5bb9a42e9703280b50c6229950998/Clash/Rules/Cloudflare.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/AI.list | awk" '{print $0 "\n"}'
          } | sed 's/ //g' | cat - | grep -v '^#' | grep -v '^$' | 
              sed 's/,no-resolve//g' | grep -Ev '^IP-CIDR6|^URL-REGEX|^PROCESS-NAME|^USER-AGENT' | sort | uniq > Rule/OpenAI.list

      - name: Check and Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
      - name: Force add changes
        run: git add Rule/OpenAI.list || true

      - name: Commit and push changes if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto Update OpenAI.list"
            git push origin HEAD:main --force
          else
            echo "No changes to commit"
          fi
