name: Merge Crypto

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delay for 10 seconds
        run: sleep 10

      - name: Ensure curl is installed
        run: |
          if ! command -v curl &> /dev/null; then
              echo "curl could not be found, installing..."
              sudo apt-get update
              sudo apt-get install -y curl
          else
              echo "curl is already installed"
          fi

      - name: Get, clean, and deduplicate domains from source files
        run: |
          {
            curl -sSfL https://raw.githubusercontent.com/yuumimi/rules/release/loon/category-cryptocurrency.txt
            curl -sSfL https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Crypto.list
            curl -sSfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Crypto/Crypto.list
            curl -sSfL https://raw.githubusercontent.com/EAlyce/conf/main/Rule/RedotPay.list
            curl -sSfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Cryptocurrency/Cryptocurrency.list
          } | grep -v '^#' | grep -v '^$' | sort | uniq | awk -F, '!seen[$0]++' > Rule/Cleaned_Crypto.list

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          
      - name: Force add changes
        run: git add Rule/Cleaned_Crypto.list || true

      - name: Commit and push changes if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update Cleaned_Crypto.list with latest domains"
            git push origin HEAD:main --force
          else
            echo "No changes to commit"
          fi
