name: Merge_Log

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  merge_domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if curl is installed
        run: |
          if ! command -v curl &> /dev/null
          then
              echo "curl is not installed, installing..."
              sudo apt-get update
              sudo apt-get install -y curl
          fi

      - name: Get domains from source files
        run: |
          curl -sL https://raw.githubusercontent.com/EAlyce/conf/main/Rule/Logsource.list | grep -v '^#' | grep -v '^$' | sort | uniq > Logsource.list.tmp
      
      - name: Add DOMAIN-SUFFIX prefix
        run: |
          sed -i 's/^/DOMAIN-SUFFIX,/' Logsource.list.tmp

      - name: Merge with existing Rule/Log.list
        run: |
          cat Logsource.list.tmp | sort | uniq >> Rule/Log.list
          sed -i 's/, /,/g' Rule/Log.list
          cat Rule/Log.list  # 调试信息：显示合并后的文件内容

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet || echo "Files have changed"
          git status  # 调试信息：显示当前 Git 状态

      - name: Set Git configuration
        if: steps.git-check.outputs.stdout != 'Files have changed'
        run: |
          git config --global user.email "msosjaahwwj@gmail.com"
          git config --global user.name "Github Action"
          git config --global user.email  # 调试信息：显示配置的 Git 用户邮箱

      - name: Commit changes
        if: steps.git-check.outputs.stdout != 'Files have changed'
        run: |
          git add Rule/Log.list
          git diff --cached --quiet || git commit -m "Merge Log"
          git push -f origin main