name: Merge Crypto

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delay for 10 seconds
        run: sleep 10

      - name: Download and combine lists from multiple sources
        run: |
          # Download and combine lists from multiple sources
          curl -sSfL https://raw.githubusercontent.com/yuumimi/rules/release/loon/category-cryptocurrency.txt \
          https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Crypto.list \
          https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Crypto/Crypto.list \
          https://raw.githubusercontent.com/EAlyce/conf/main/Rule/RedotPay.list \
          https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Cryptocurrency/Cryptocurrency.list \
          | grep -v '#' | grep -v '^$' | \
          # Remove non-printing characters and extra spaces
          tr -d '\r' | tr -d '\t' | tr -s ' ' > Rule/Crypto.list

          # Print the first few lines of the file for debugging
          echo "Contents of Rule/Crypto.list after initial download and cleaning:"
          head -n 10 Rule/Crypto.list

      - name: Fetch and integrate lists from LeiyuG/Surge repository's rules directory
        run: |
          # Fetch the list of files from LeiyuG/Surge repository
          curl -s https://api.github.com/repos/LeiyuG/Surge/contents/rules | \
          grep '"download_url"' | \
          cut -d '"' -f 4 | \
          grep '\.list$' | \
          while read -r file; do
            echo "Fetching $file"
            curl -sSfL "$file" | grep -v '#' | grep -v '^$' | tr -d '\r' | tr -d '\t' | tr -s ' ' >> Rule/Crypto.list
          done

          # Print the first few lines of the file for debugging
          echo "Contents of Rule/Crypto.list after fetching LeiyuG/Surge lists:"
          head -n 10 Rule/Crypto.list

      - name: Clean and preprocess the list
        run: |
          sed -i -e '/[\/\*]/d' -e '/#/d' Rule/Crypto.list

          # Print the first few lines of the file for debugging
          echo "Contents of Rule/Crypto.list after cleaning and preprocessing:"
          head -n 10 Rule/Crypto.list

      - name: Final deduplication and sorting
        run: |
          # Remove duplicates and sort the list
          sort Rule/Crypto.list | uniq > Rule/Crypto.list

          # Print the first few lines of the file for debugging
          echo "Contents of Rule/Crypto.list after deduplication and sorting:"
          head -n 10 Rule/Crypto.list

      - name: Check if there are changes
        run: |
          git status
          git diff

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          
      - name: Commit and push changes if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Rule/Crypto.list
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update Crypto.list"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
