name: Merge_Log

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  merge_domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if curl is installed
        run: |
          if ! command -v curl &> /dev/null
          then
              echo "curl is not installed, installing..."
              sudo apt-get update
              sudo apt-get install -y curl
          fi

      - name: Get domains from source files
        run: |
          curl -sL https://raw.githubusercontent.com/EAlyce/conf/main/Rule/Logsource.list?$(date +%s) | grep -v '^#' | grep -v '^$' | sort | uniq > Logsource.list.tmp
      
      - name: Add DOMAIN-SUFFIX prefix
        run: |
          sed -i 's/^/DOMAIN-SUFFIX,/' Logsource.list.tmp

      - name: Merge with existing Rule/Log.list
        run: |
          while IFS= read -r line; do
            echo "DOMAIN-SUFFIX,$line" >> Rule/Log.list
          done < Logsource.list.tmp
          sort -o Rule/Log.list Rule/Log.list  # 自动排序

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "Files have changed"
          git status  # 调试信息：显示当前 Git 状态

      - name: Set Git configuration
        if: steps.git-check.outputs.exit-code != 0
        run: |
          git config --global user.email "msosjaahwwj@gmail.com"
          git config --global user.name "Github Action"
          git config --global user.email  # 调试信息：显示配置的 Git 用户邮箱

      - name: Commit changes
        if: steps.git-check.outputs.exit-code != 0
        run: |
          git add Rule/Log.list
          git diff --cached --quiet || git commit -m "Merge Log"
          git push -f origin main