name: Merge Crypto

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  

      - name: Get, clean, and deduplicate domains
        run: |
          {
           curl -sSfL "https://raw.githubusercontent.com/yuumimi/rules/release/loon/category-cryptocurrency.txt" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Crypto.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Crypto/Crypto.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/EAlyce/conf/main/Rule/RedotPay.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Cryptocurrency/Cryptocurrency.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Binance.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Binancenew.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Bitfinex.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/FSMOne.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Gate.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/HTX.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Kraken.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Kucoin.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Nexo.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Pionex.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/TR.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/HongKongBank.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/IBKR.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Trading212.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Vodafone-wificall.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/NigeriaBank.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Bitget.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Coinbase.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Bybit.list" | awk '{print $0 "\n"}'
          } | sed 's/ //g' | cat - | grep -v '^#' | grep -v '^$' | sed 's/,no-resolve//g' | grep -Ev '^IP-CIDR6|^URL-REGEX|^PROCESS-NAME|^USER-AGENT' | grep -v '^#' | sort | uniq > Rule/Crypto.list

      - name: Check if there are changes
        run: |
          git status
          git diff  # 这两个命令检查本地更改，确保脚本正确处理更改

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and push changes if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token 进行身份验证
        run: |
          git add Rule/Crypto.list
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update Crypto.list"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi  # 确保 if 语句正确闭合
