name: Merge_China_All.list_to_Rule_DIRECT.list

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'

jobs:
  merge_domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if curl is installed
        run: |
          if ! command -v curl &> /dev/null
          then
              echo "curl is not installed, installing..."
              sudo apt-get update
              sudo apt-get install -y curl
          fi

      - name: Get domains from source file
        run: |
          curl -s https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/China/China_All.list | grep -v '^#' | grep -v '^$' | sort | uniq > DIRECT.tmp
          curl -s https://raw.githubusercontent.com/Blankwonder/surge-list/master/cn.list | grep -v '^#' | grep -v '^$' | sort | uniq >> DIRECT.tmp

      - name: Merge with existing DIRECT.list
        run: |
          mv DIRECT.tmp Rule/DIRECT.list

      - name: Set Git configuration
        run: |
          git config --global user.email "msosjaahwwj@gmail.com"
          git config --global user.name "EAlyce"

      - name: Commit changes
        run: |
          if [[ -n $(git status -s) ]]; then
            git commit -m "Merge China_All.list to Rule/DIRECT.list"
            git push origin main
          else
            echo "No changes to commit"
          fi
