name: Merge Proxy

on:
  push:
    branches:
      - main

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delay for 10 seconds
        run: sleep 10
        
      - name: Ensure curl is installed
        run: |
          if ! command -v curl &> /dev/null
          then
              echo "curl could not be found, installing..."
              sudo apt-get update
              sudo apt-get install -y curl
          else
              echo "curl is already installed"
          fi
          
      - name: Get domains from source file and merge
        run: |
          curl -sSfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Global/Global_All.list |
          grep -v '^#' |
          grep -v '^$' |
          sort |
          uniq > Rule/Proxy.list

          curl -sSfL https://ruleset.skk.moe/List/non_ip/stream.conf |
          grep -v '^#' |
          grep -v '^$' |
          sort |
          uniq >> Rule/Proxy.list

          curl -sSfL https://ruleset.skk.moe/List/non_ip/cdn.conf |
          grep -v '^#' |
          grep -v '^$' |
          sort |
          uniq >> Rule/Proxy.list

          curl -sSfL https://ruleset.skk.moe/List/non_ip/global.conf |
          grep -v '^#' |
          grep -v '^$' |
          sort |
          uniq >> Rule/Proxy.list

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git branch -a
          git status
          
      - name: Check for changes
        run: |
          git diff --exit-code || exit 0

      - name: Commit and force push to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Rule/Proxy.list
          git commit -m "Auto Update Proxy.list"
          git push origin HEAD:main --force