name: Merge Proxy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delay for 10 seconds
        run: sleep 10

      - name: Ensure curl is installed
        run: |
          if ! command -v curl &> /dev/null
          then
              echo "curl could not be found, installing..."
              sudo apt-get update
              sudo apt-get install -y curl
          else
              echo "curl is already installed"
          fi

      - name: Get domains from source files and merge
        run: |
          curl -sSfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Global/Global_All.list |
          grep -v '^#' |
          grep -v '^$' |
          sort |
          uniq > Rule/Proxy.list

          curl -sSfL https://ruleset.skk.moe/List/non_ip/stream.conf |
          grep -v '^#' |
          grep -v '^$' |
          sort |
          uniq >> Rule/Proxy.list

          curl -sSfL https://ruleset.skk.moe/List/non_ip/cdn.conf |
          grep -v '^#' |
          grep -v '^$' |
          sort |
          uniq >> Rule/Proxy.list

          curl -sSfL https://ruleset.skk.moe/List/non_ip/global.conf |
          grep -v '^#' |
          grep -v '^$' |
          sort |
          uniq >> Rule/Proxy.list

          awk -F, '{split($NF, parts, "."); if(length(parts)>2) {domain=parts[length(parts)-1]"."parts[length(parts)]} else {domain=$NF}; gsub(/[^a-zA-Z0-9.-]/, "", domain); if (domain !~ /xn--/) print "DOMAIN-SUFFIX,"domain}' Rule/Proxy.list | sort | uniq > Rule/Proxy_cleaned.list

          mv Rule/Proxy_cleaned.list Rule/Proxy.list

      - name: Check and Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git diff --quiet || echo "Files have changed"
          git status

      - name: Force add changes
        run: git add Rule/Proxy.list

      - name: Commit and force push to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git commit -m "Auto Update Proxy.list"
          git push origin HEAD:main --force