name: Merge_AI

on:
  push:
    branches:
      - main

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delay for 10 seconds
        run: sleep 10

      - name: Check if curl is installed
        run: |
          if ! command -v curl &> /dev/null
          then
              echo "curl is not installed, installing..."
              sudo apt-get update
              sudo apt-get install -y curl
          fi

      - name: Get domains from source files
        run: |
          curl -sL https://ruleset.skk.moe/List/non_ip/ai.conf | grep -v '^#' | grep -v '^$' | sort | uniq > ai.conf.tmp
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list | grep -v '^#' | grep -v '^$' | sort | uniq > OpenAI.list.tmp
          curl -sL https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Loon/Rule/AI.list | grep -v '^#' | grep -v '^$' | sort | uniq > AI.list.tmp
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Copilot/Copilot.list | grep -v '^#' | grep -v '^$' | sort | uniq > Copilot.list.tmp
          curl -sL https://raw.githubusercontent.com/Repcz/Tool/974e9a365c00bb30b00ee8054968047ea6072caa/Surge/Rules/AI.list | grep -v '^#' | grep -v '^$' | sort | uniq > Repcz.list.tmp
          curl -sL https://raw.githubusercontent.com/EAlyce/conf/main/Rule/ai.list | grep -v '^#' | grep -v '^$' | sort | uniq > ai.list.tmp
          curl -sL https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/AI.list | grep -v '^#' | grep -v '^$' | sort | uniq > shenjiai.list.tmp
      - name: Merge with existing Rule/OpenAI.list
        run: |
          cat ai.conf.tmp OpenAI.list.tmp shenjiai.list.tmp AI.list.tmp Copilot.list.tmp Repcz.list.tmp ai.list.tmp | sort | uniq > Rule/OpenAI.list
          sed -i 's/, /,/g' Rule/OpenAI.list
          cat Rule/OpenAI.list  # 调试信息：显示合并后的文件内容

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet || echo "Files have changed"
          git status  # 调试信息：显示当前 Git 状态

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git branch -a
          git status
      - name: Commit and force push to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Rule/OpenAI.list
          git commit -m "OpenAI"
          git push origin HEAD:main --force
