name: Merge Proxy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delay for 10 seconds
        run: sleep 10

      - name: Ensure curl is installed
        run: |
          if ! command -v curl &> /dev/null
          then
              echo "curl could not be found, installing..."
              sudo apt-get update
              sudo apt-get install -y curl
          else
              echo "curl is already installed"
          fi

      - name: Get and process domains
        run: |
          for url in \
            "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Global/Global_All.list" \
             "https://raw.githubusercontent.com/axcsz/Collect/master/Ruleset/GlobalGFW.list" \
            "https://ruleset.skk.moe/List/non_ip/stream.conf" \
            "https://ruleset.skk.moe/List/non_ip/cdn.conf" \
            "https://ruleset.skk.moe/List/non_ip/global.conf"; do
            curl -sSfL $url
          done | grep -v '^#' | grep -v '^$' | sort | uniq |
          awk -F, '{
              split($NF, parts, ".")
              if (length(parts) > 2) {
                  domain = parts[length(parts)-1] "." parts[length(parts)]
              } else {
                  domain = $NF
              }
              gsub(/[^a-zA-Z0-9.-]/, "", domain)
              if (domain ~ /^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/ && domain !~ /xn--/) {
                  print "DOMAIN-SUFFIX," domain
              }
          }' | sort | uniq > Rule/Proxy.list

      - name: Check and Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git status

      - name: Force add changes
        run: git add Rule/Proxy.list

      - name: Commit and force push to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git commit -m "Auto Update Proxy.list"
          git push origin HEAD:main --force