name: Merge China

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  merge_domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if curl is installed
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Get domains from source file
        run: |
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/China/China_All.list | grep -v '^#' | grep -v '^$' | sort | uniq > Rule/DIRECT.tmp

      - name: Merge with existing DIRECT.list
        run: |
          mv Rule/DIRECT.tmp Rule/DIRECT.list

      - name: Set Git configuration
        run: |
          git config --global user.email "msosjaahwwj@gmail.com"
          git config --global user.name "Github Action"
          
      - name: Commit changes
        run: |
          git add Rule/DIRECT.list
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git commit -m "合并DIRECT完成"
            git push origin main
          fi