name: Merge Proxy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delay for 10 seconds
        run: sleep 10

      - name: Ensure curl is installed
        run: |
          if ! command -v curl &> /dev/null
          then
              echo "curl could not be found, installing..."
              sudo apt-get update
              sudo apt-get install -y curl
          else
              echo "curl is already installed"
          fi

      - name: Get and process domains
        run: |
         {
         curl -sSfL "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Global/Global_All.list" | awk '{print $0 "\n"}'
         curl -sSfL "https://raw.githubusercontent.com/axcsz/Collect/master/Ruleset/GlobalGFW.list" | awk '{print $0 "\n"}'
         curl -sSfL "https://ruleset.skk.moe/List/non_ip/stream.conf" | awk '{print $0 "\n"}'
         curl -sSfL "https://ruleset.skk.moe/List/non_ip/cdn.conf" | awk '{print $0 "\n"}'
         curl -sSfL "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/ProxyLite.list" | awk '{print $0 "\n"}'
         curl -sSfL "https://ruleset.skk.moe/List/non_ip/global.conf" | awk '{print $0 "\n"}'
         curl -sSfL "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/ProxyMedia.list" | awk '{print $0 "\n"}'
         curl -sSfL "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ProxyGFWlist.list" | awk '{print $0 "\n"}'
         } | cat - | grep -v '^#' | grep -v '^$' | \
         sed -E 's/^DOMAIN,([^,]+)$/DOMAIN-SUFFIX,\1/' | \
         awk -F',' '{
          if ($1 == "DOMAIN-SUFFIX,") {
            split($2, parts, ".");
            if (length(parts) > 2) {
              $2 = parts[length(parts)-1] "." parts[length(parts)];
            }
          }
          print $0;
         }' | \
         sed 's/,no-resolve//g' | grep -Ev '^IP-CIDR6|^URL-REGEX|^PROCESS-NAME|^USER-AGENT' | \
         awk '{
         if ($0 ~ /^DOMAIN-SUFFIX,/) {
         domain = $0;
         sub(/^DOMAIN-SUFFIX,/, "", domain);          # 去掉前缀 DOMAIN-SUFFIX,
         n = split(domain, parts, ".");               # 分割域名
         if (n > 2) {
            print "DOMAIN-SUFFIX," parts[n-1] "." parts[n]; # 只打印二级域名
         } else {
            print $0;                                # 保留不符合条件的域名
         }
         } else {
         print $0;                                    # 保留非 DOMAIN-SUFFIX 行
         }
         }' | awk -F, '
         BEGIN {
         # 创建一个数组存储 DOMAIN-KEYWORD 的关键词
         keyword_count = 0;
         }
         /^DOMAIN-KEYWORD,/ {
         # 提取 DOMAIN-KEYWORD 的关键词
         keywords[keyword_count++] = $2;
         next;
         }
         /^DOMAIN-SUFFIX,/ {
          # 检查 DOMAIN-SUFFIX 是否包含任意一个 DOMAIN-KEYWORD
         for (i = 0; i < keyword_count; i++) {
         if (index($2, keywords[i]) > 0) {
            # 如果 DOMAIN-SUFFIX 包含 DOMAIN-KEYWORD，则跳过此行
            next;
         }
         }
         }
         {
         # 打印所有不符合过滤条件的行
         print;
         }
         ' Rule/Proxy.list > temp && mv temp Rule/Proxy.list

      - name: Check and Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git status

      - name: Force add changes
        run: git add Rule/Proxy.list || true

      - name: Commit and push changes if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto Update Proxy.list"
            git push origin HEAD:main --force
          else
            echo "No changes to commit"
          fi
