name: Merge DIRECT

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get and process China domains
        run: |
          {
            curl -sSfL "https://ruleset.skk.moe/List/non_ip/domestic.conf" | awk '{print $0 "\n"}'
            curl -sSfL "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/ChinaDomain.list" | awk '{print $0 "\n"}'
            curl -sSfL "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/China/China_All.list" | awk '{print $0 "\n"}'
            curl -sSfL "https://raw.githubusercontent.com/DH-Teams/DH-Geo_AS_IP_CN/refs/heads/main/Geo_AS_IP_CN_V4_Surge.list" | awk '{print $0 "\n"}'
            curl -sSfL "https://raw.githubusercontent.com/menaknak/adns_depend/5d02499ef1216702ae4a99d14057f2e5defe6485/input/%E9%87%8D%E7%82%B9%E5%9F%9F%E5%90%8D14860_20231230.txt" | sed 's/^/DOMAIN-SUFFIX,/' | awk '{print $0 "\n"}'
            curl -sSfL "https://github.com/Lucius-Pan/confStore/raw/main/Extra-Direct.conf" | sed 's/,DIRECT$//' | awk '{print $0 "\n"}'
            curl -sSfL "https://github.com/Lucius-Pan/confStore/raw/main/QQ-conf-IP-CIDR.conf" | sed 's/,DIRECT$//' | awk '{print $0 "\n"}'
            curl -sSfL "https://github.com/Lucius-Pan/confStore/raw/main/wechat-conf-IP-CIDR.conf" | sed 's/,DIRECT$//' | awk '{print $0 "\n"}'
          } | awk -F',' '
            # 删除空行和注释
            NF && !/^#/ {
                # 去掉多余的空格
                gsub(/ /, "");
                
                # 处理 DOMAIN 和去掉 no-resolve
                gsub(/,no-resolve/, "");
                
                # 将单独的 DOMAIN 改为 DOMAIN-SUFFIX
                if ($1 == "DOMAIN") {
                    $1 = "DOMAIN-SUFFIX";
                }
                
                # 过滤不需要的类型
                if (!/^(IP-CIDR6|URL-REGEX|PROCESS-NAME|USER-AGENT)/) {
                    print $1 "," $2
                }
            }
          ' | sort -u > Rule/DIRECT.list
          
      - name: Check and Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git status

      - name: Force add changes
        run: git add Rule/DIRECT.list || true

      - name: Commit and push changes if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto Update DIRECT.list"
            git push origin HEAD:main --force
          else
            echo "No changes to commit"
          fi
