name: Merge DIRECT

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delay for 10 seconds
        run: sleep 10

      - name: Ensure curl is installed
        run: |
          if ! command -v curl &> /dev/null; then
              echo "curl could not be found, installing..."
              sudo apt-get update
              sudo apt-get install -y curl
          else
              echo "curl is already installed"
          fi

      - name: Get and process China domains
        run: |
          { 
          curl -sSfL https://ruleset.skk.moe/List/non_ip/domestic.conf
          curl -sSfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/China/China_All.list
          curl -sSfL https://raw.githubusercontent.com/menaknak/adns_depend/5d02499ef1216702ae4a99d14057f2e5defe6485/input/%E9%87%8D%E7%82%B9%E5%9F%9F%E5%90%8D14860_20231230.txt | sed 's/^/DOMAIN-SUFFIX,/'
          curl -sSfL https://github.com/Lucius-Pan/confStore/raw/main/Extra-Direct.conf | sed 's/,DIRECT$//'
          curl -sSfL https://github.com/Lucius-Pan/confStore/raw/main/QQ-conf-IP-CIDR.conf | sed 's/,DIRECT$//'
          curl -sSfL https://github.com/Lucius-Pan/confStore/raw/main/wechat-conf-IP-CIDR.conf | sed 's/,DIRECT$//'
          } | grep -v '^#' | grep -v '^$' | sort | uniq > Rule/DIRECT.list
          
      - name: Check and Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git status

      - name: Force add changes
        run: git add Rule/DIRECT.list || true

      - name: Commit and push changes if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto Update DIRECT.list"
            git push origin HEAD:main --force
          else
            echo "No changes to commit"
          fi
