name: Merge BanIP

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delay for 10 seconds
        run: sleep 10

      - name: Ensure curl is installed
        run: |
          if ! command -v curl &> /dev/null
          then
              echo "curl could not be found, installing..."
              sudo apt-get update
              sudo apt-get install -y curl
          else
              echo "curl is already installed"
          fi

      - name: Get and process domains
        run: |
          mkdir -p Rule
          for url in \
            "https://raw.githubusercontent.com/BlueSkyXN/Comprehensive-Network-Defense/master/IPs/SKY-BAN-IP.txt" \
            "https://raw.githubusercontent.com/BlueSkyXN/Comprehensive-Network-Defense/master/IPs/SKY-FUCK-IP.txt"; do
            curl -sSfL $url
          done | tr -d '\r' | grep -v '^#' | grep -v '^$' > combined_list.txt

      - name: Validate and process IP addresses
        run: |
          mkdir -p Rule
          awk '{ if ($0 !~ /\/[0-9]+$/) print $0"/32"; else print $0 }' combined_list.txt |
          sed 's/^/IP-CIDR,/' | \
          awk -F, '{ if ($2 ~ /^(?:[0-9]{1,3}\.){3}[0-9]{1,3}\/[0-9]{1,2}$/) print $1","$2 }' > Rule/BanIP.list

      - name: Check and Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git status

      - name: Force add changes
        run: git add Rule/BanIP.list

      - name: Conditionally Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff-index --quiet HEAD; then
              git commit -m "Auto Update BanIP.list"
              git push origin HEAD:main --force
          else
              echo "No changes to commit"
          fi
