name: Merge Crypto

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 检查是否使用了最新的 checkout action

      - name: Delay for 10 seconds
        run: sleep 10  # 这个步骤没有问题，但如果没有必要可以移除

      - name: Get, clean, and deduplicate domains
        run: |
          # 下载并清理数据源
          curl -sSfL \
          https://raw.githubusercontent.com/yuumimi/rules/release/loon/category-cryptocurrency.txt \
          https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Crypto.list \
          https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Crypto/Crypto.list \
          https://raw.githubusercontent.com/EAlyce/conf/main/Rule/RedotPay.list \
          https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Cryptocurrency/Cryptocurrency.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Binance.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Binancenew.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Bitfinex.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/FSMOne.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Gate.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/HTX.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Kraken.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Kucoin.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Nexo.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Pionex.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/TR.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/HongKongBank.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/IBKR.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Trading212.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Vodafone-wificall.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/NigeriaBank.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Bitget.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Coinbase.list \
          https://raw.githubusercontent.com/LeiyuG/Surge/main/rules/Bybit.list | \
          grep -v '^#' | grep -v '^$' | \
          tr -d '\r' | tr -d '\t' | tr -s ' ' | \
          grep -E '^IP-CIDR|^DOMAIN,' | \
          grep -vE '^DOMAIN,.*/|\*' | \
          sed '/^DOMAIN,/s/^DOMAIN,/DOMAIN-KEYWORD,/' | \
          grep -vE '^(PROCESS-NAME|USER-AGENT)' | \
          sort -u > Rule/Crypto.list

      - name: Check if there are changes
        run: |
          git status
          git diff  # 这两个命令检查本地更改，确保脚本正确处理更改

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"  # 配置 Git 用户信息

      - name: Commit and push changes if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token 进行身份验证
        run: |
          git add Rule/Crypto.list
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update Crypto.list"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi  # 确保 if 语句正确闭合
