name: Merge_AI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  merge_domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if curl is installed
        run: |
          if ! command -v curl &> /dev/null
          then
              echo "curl is not installed, installing..."
              sudo apt-get update
              sudo apt-get install -y curl
          fi

      - name: Get domains from source files
        run: |
          curl -sL https://ruleset.skk.moe/List/non_ip/ai.conf | grep -v '^#' | grep -v '^$' | sort | uniq > ai.conf.tmp
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list | grep -v '^#' | grep -v '^$' | sort | uniq > OpenAI.list.tmp
          curl -sL https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Loon/Rule/AI.list | grep -v '^#' | grep -v '^$' | sort | uniq > AI.list.tmp
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Copilot/Copilot.list | grep -v '^#' | grep -v '^$' | sort | uniq > Copilot.list.tmp
          curl -sL https://raw.githubusercontent.com/Repcz/Tool/974e9a365c00bb30b00ee8054968047ea6072caa/Surge/Rules/AI.list | grep -v '^#' | grep -v '^$' | sort | uniq > Repcz.list.tmp
      - name: Merge with existing Rule/OpenAI.list
        run: |
          cat ai.conf.tmp OpenAI.list.tmp AI.list.tmp Copilot.list.tmp Repcz.list.tmp | sort | uniq > Rule/OpenAI.list
          sed -i 's/, /,/g' Rule/OpenAI.list
          cat Rule/OpenAI.list  # 调试信息：显示合并后的文件内容

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet || echo "Files have changed"
          git status  # 调试信息：显示当前 Git 状态

      - name: Set Git configuration
        if: steps.git-check.outputs.stdout != 'Files have changed'
        run: |
          git config --global user.email "msosjaahwwj@gmail.com"
          git config --global user.name "EAlyce"
          git config --global user.email  # 调试信息：显示配置的 Git 用户邮箱

      - name: Commit changes
        if: steps.git-check.outputs.stdout != 'Files have changed'
        run: |
          git add Rule/OpenAI.list
          git diff --cached --quiet || git commit -m "Merge OpenAI lists to Rule/OpenAI.list"
          git push -f origin main
