name: Merge Crypto

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delay for 10 seconds
        run: sleep 10

      - name: Get and clean domains from source files
        run: |
          {
            curl -sSfL https://raw.githubusercontent.com/yuumimi/rules/release/loon/category-cryptocurrency.txt
            curl -sSfL https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Crypto.list
            curl -sSfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Crypto/Crypto.list
            curl -sSfL https://raw.githubusercontent.com/EAlyce/conf/main/Rule/RedotPay.list
            curl -sSfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Cryptocurrency/Cryptocurrency.list
          } > combined_sources.txt

      - name: Process and deduplicate the combined file
        run: |
          cat combined_sources.txt | grep -v '^#' | grep -v '^$' | sort | uniq > Rule/Crypto.list

      - name: Remove temporary file
        run: rm combined_sources.txt

      - name: Check if there are changes
        run: |
          git status
          git diff

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          
      - name: Commit and push changes if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Rule/Crypto.list
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update Crypto.list"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
