name: Remove Duplicate Entries

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  merge_domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Log.list file
        run: |
          curl -sL https://raw.githubusercontent.com/EAlyce/conf/main/Rule/Log.list > Log.tmp

      - name: Remove duplicate entries
        run: |
          awk '!seen[$0]++' Log.tmp > Log.list
          rm Log.tmp

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet || echo "Files have changed"

      - name: Set Git configuration and commit changes
        if: steps.git-check.outputs.stdout != 'Files have changed'
        run: |
          git config --global user.email "msosjaahwwj@gmail.com"
          git config --global user.name "Github Action"
          git add Rule/Log.list
          git diff --cached --quiet || git commit -m "Remove Duplicate Entries"
          git pull origin main --ff-only || echo "Merge conflict"
          git checkout --theirs .
          git add .
          git commit -m "Auto-resolve merge conflict"
          git push origin main