name: Remove Duplicates

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  remove_duplicates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download target file
        run: |
          curl -sSL -o Log.list https://raw.githubusercontent.com/EAlyce/conf/main/Rule/Log.list

      - name: Remove duplicates
        run: |
          awk '!seen[$0]++' Log.list > Log.tmp
          mv Log.tmp Log.list

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Log.list
          git commit -m "Remove duplicates from Log.list"
          git push