name: Real-time File Processing

on:
  push:
    branches:
      - main

jobs:
  process_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download target file
        run: |
          curl -sSL -o target_file.txt https://raw.githubusercontent.com/EAlyce/conf/main/Rule/Log.list

      - name: Remove duplicates
        run: |
          awk '!seen[$0]++' target_file.txt > target_file.tmp
          mv target_file.tmp target_file.txt

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout main
          cat target_file.txt > Log.list
          git add Log.list
          git commit -m "Remove duplicates from Log.list"
          git push