name: Merge WeChat

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deduplicate_and_remove_empty_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get and merge domains from source files
        run: |
          {
           curl -sSfL "https://github.com/xOS/Config/raw/7bf4ffd3a2f5da8b967d9c1b5e0f5c79609b1047/RuleSet/WeChat.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/WeChat/WeChat.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/unknowntokyo/surge-list/master/wechat.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Wechat.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://raw.githubusercontent.com/NobyDa/Script/master/Surge/WeChat.list" | awk '{print $0 "\n"}'
           curl -sSfL "https://github.com/Lucius-Pan/confStore/raw/main/wechat-conf-IP-CIDR.conf" | awk '{print $0 "\n"}'
          } | sed 's/ //g' | grep -v '^#' | grep -v '^$' | 
              sed 's/,no-resolve//g' |
              sed 's/^DOMAIN-KEYWORD,\([0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.\)$/IP-CIDR,\1/g' |
              sort | uniq > Rule/WeChat.list

      - name: Check and Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
      - name: Force add changes
        run: git add Rule/WeChat.list || true

      - name: Commit and push changes if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto Update WeChat.list"
            git push origin HEAD:main --force
          else
            echo "No changes to commit"
          fi
